# Created by: Eric Allen Griff <setjmp@hotmail.com>
# $FreeBSD$

PORTNAME=	kibana
PORTVERSION=	4.1.0
DISTVERSIONSUFFIX=	-snapshot-darwin-x64
CATEGORIES=	setjmp
MASTER_SITES=	http://download.elastic.co/kibana/kibana/

MAINTAINER=	setjmp@hotmail.com
COMMENT=	Kibana

LICENSE=	APACHE20
NO_BUILD=	YES

.include <bsd.port.mk>
