# $FreeBSD$

PORTNAME=	jruby
DISTVERSIONPREFIX=	src-
DISTVERSIONSUFFIX=	.pre2
PORTVERSION=	9.0.0.0
CATEGORIES=	setjmp lang
MASTER_SITES=	https://s3.amazonaws.com/jruby.org/downloads/9.0.0.0.pre2/

MAINTAINER=
COMMENT=

.include <bsd.port.mk>

