# Created by: Eric Allen Griff <setjmp@hotmail.com>
# $FreeBSD$

PORTNAME=	IPASuite
PORTVERSION=	0.5.2
DISTNAME=	ipa-0.5.2
MASTER_SITES=	https://tools.netsa.cert.org/releases/
CATEGORIES=	setjmp net-mgmt databases

MAINTAINER=	setjmp@hotmail.com
COMMENT=	CERT NETSA IPA Suite

LICENSE=	GPLv2

.include <bsd.port.mk>
