# Created by: Eric Allen Griff <setjmp@hotmail.com>
# $FreeBSD$

PORTNAME=	IPASuite
PORTVERSION=	0.5.2
CATEGORIES=	setjmp net-mgmt databases
MASTER_SITES=	http://tools.netsa.cert.org/releases/
DISTNAME=	ipa-0.5.2

MAINTAINER=	setjmp@hotmail.com
COMMENT=	CERT NETSA IPA Suite

LICENSE=	GPLv2

GNU_CONFIGURE=	YES
.include <bsd.port.mk>
