--- config/kibana.yml.orig	2015-06-03 00:40:52 UTC
+++ config/kibana.yml
@@ -57,11 +57,11 @@ verify_ssl: true
 # ssl_cert_file: /path/to/your/server.crt
 
 # Set the path to where you would like the process id file to be created.
-# pid_file: /var/run/kibana.pid
+pid_file: /var/run/kibana.pid
 
 # If you would like to send the log output to a file you can set the path below.
 # This will also turn off the STDOUT log output.
-# log_file: ./kibana.log
+log_file: /var/log/kibana.log
 
 # Plugins that are included in the build, and no longer found in the plugins/ folder
 bundled_plugin_ids:
@@ -74,4 +74,4 @@ bundled_plugin_ids:
  - plugins/settings/index
  - plugins/table_vis/index
  - plugins/vis_types/index
- - plugins/visualize/index
\ No newline at end of file
+ - plugins/visualize/index
