# Created by: Eric Allen
# $FreeBSD$

PORTNAME=	kibana
PORTVERSION=	4.0.2
CATEGORIES=	setjmp textproc
MASTER_SITES=	http://download.elastic.co/kibana/kibana/
DISTVERSIONSUFFIX=	-darwin-x64

MAINTAINER=	setjmp@hotmail.com
COMMENT=	dashboard interface to elasticsearch indexes version 4

.include <bsd.port.mk>

