# Created by: Eric Allen Griff <setjmp@hotmail.com>
# $FreeBSD$

PORTNAME=	yaf_file_mediator
PORTVERSION=	1.1.0
CATEGORIES=	net-mgmt
MASTER_SITES=	http://tools.netsa.cert.org/confluence/download/attachments/15958024/

MAINTAINER=	setjmp@hotmail.com
COMMENT=	YAF file mediator

GNU_CONFIGURE=	YES

.include <bsd.port.mk>
