# Created by: Eric Allen Griff <setjmp@hotmail.com>
# $FreeBSD$

PORTNAME=	netsa-python
PORTVERSION=	1.4.3
MASTER_SITES=	http://tools.netsa.cert.org/releases/
CATEGORIES=	setjmp
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

.include <bsd.port.mk>
