# Created by: Eric Allen Griff <setjmp@hotmail.com>
# $FreeBSD$

PORTNAME=	orcus
PORTVERSION=	1.0.3
CATEGORIES=	setjmp net-mgmt
MASTER_SITES=	http://tools.netsa.cert.org/releases/

MAINTAINER=	setjmp@hotmail.com
COMMENT=	NETSA super_mediator

LICENSE=	GPLv2

LIB_DEPENDS=	libfixbuf.so:${PORTSDIR}/setjmp/libfixbuf

USES=	python
USE_PYTHON=	distutils autoplist
.include <bsd.port.mk>
