# Created by: Eric Allen Griff <setjmp@hotmail.com>
# $FreeBSD$

PORTNAME=	analysis-pipeline
PORTVERSION=	4.4.1
CATEGORIES=	setjmp net-mgmt databases
MASTER_SITES=	http://tools.netsa.cert.org/releases/

MAINTAINER=	setjmp@hotmail.com
COMMENT=	CERT NETSA IPA Suite

LICENSE=	GPLv2

GNU_CONFIGURE=	YES
.include <bsd.port.mk>
