# Created by: Eric Allen Griff <setjmp@hotmail.com>
# $FreeBSD$

PORTNAME=	rayon
PORTVERSION=	1.4.3
CATEGORIES=	setjmp
MASTER_SITES=	http://tools.netsa.cert.org/releases/
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	setjmp@hotmail.com
COMMENT=	CERT NETSA rayon SiLK Tools Visualization Tools

LICENSE=	GPLv2

USES=	python
USE_PYTHON=	distutils autoplist
.include <bsd.port.mk>
