# Created by: Eric Allen Griff <setjmp@hotmail.com>
# $FreeBSD$

PORTNAME=	super_mediator
PORTVERSION=	1.1.1
CATEGORIES=	setjmp net-mgmt
MASTER_SITES=	http://tools.netsa.cert.org/releases/

MAINTAINER=	setjmp@hotmail.com
COMMENT=	NETSA super_mediator

LICENSE=	GPLv2

LIB_DEPENDS=	libfixbuf.so:${PORTSDIR}/setjmp/libfixbuf

GNU_CONFIGURE=	YES
INSTALL_TARGET=	install-strip
USES=		libtool pathfix pkgconfig
USE_GNOME=	glib20

.include <bsd.port.mk>
