--- config/kibana.yml.orig	2015-06-05 06:31:38 UTC
+++ config/kibana.yml
@@ -50,7 +50,7 @@ verify_ssl: true
 # ssl_cert_file: /path/to/your/server.crt
 
 # Set the path to where you would like the process id file to be created.
-# pid_file: /var/run/kibana.pid
+pid_file: /var/run/kibana.pid
 
 # Plugins that are included in the build, and no longer found in the plugins/ folder
 bundled_plugin_ids:
@@ -63,4 +63,4 @@ bundled_plugin_ids:
  - plugins/settings/index
  - plugins/table_vis/index
  - plugins/vis_types/index
- - plugins/visualize/index
\ No newline at end of file
+ - plugins/visualize/index
